name: dnamexpress-wgr
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - snakemake
  - fastqc
  - trim-galore
  - bismark
  - bowtie2
  - star
  - hisat2
  - samtools
  - multiqc
  - subread
  - deeptools
  - r-base
  - r-deseq2
  - r-edger
  - r-methylkit
  - r-dss
  - r-ggplot2
  - r-data.table
  - r-tidyverse
  - r-optparse
